### ISSUE TITLE
Optimistic updates?

### ISSUE THREAD

**Issue by mshwery** [GoThinkster/redux-review#13]
It's difficult to grok where (if at all) this example shows off good patterns for optimistic updates, i.e. a user submits a comment and it appears in the UI as if the comment was successfully posted _immediately_, meanwhile the async request is sent. Successful responses would need not do anything to update the state (or UI) since we optimistically assumed the update would succeed, but failure responses would require prompting the user with an error or retry message.

**Comment by vkarpov15** [comment]
I'm targetting this guide to be more for beginner/intermediate devs, so I'm looking to avoid diving in to any performance debugging. Thanks for the suggestion though.
