### ISSUE TITLE
Needs Documentation

### ISSUE THREAD

**Issue by mshwery** [GoThinkster/redux-review#14]
I don't really see _any_ documentation in the code, which is really important if this is to be an example of using redux in a real-world application.

**Comment by EricSimons** [comment]
Docs are being worked on right now; priority has been around codebase finalization until recently

**Comment by EricSimons** [comment]
This was also explained in the README, so I'm going to close this issue.

**Comment by mshwery** [comment]
ah, thanks for the clarification!
