### ISSUE TITLE
Articles not appearing on newly cloned repo

### ISSUE THREAD

**Issue by jamesmbowler** [GoThinkster/redux-review#19]
See
[https://drive.google.com/file/d/0B3J7t9DdAoVXS0c5QjB6ckNYNVE/view?usp=sharing](url)

I just cloned the repo, and started the server on local.

Btw, this looks awesome, thanks!

**Comment by daniel1943** [comment]
src/components/ArticlePreview.js

Last line(80), change:

export default connect(() => ({}), mapDispatchToProps)(ArticleActions);

To:

export default connect(() => ({}), mapDispatchToProps)(ArticlePreview);

**Comment by jamesmbowler** [comment]
Thanks!
